name: dio_http_util
description: A powerful HTTP utility package based on Dio with configurable header injection and unified error handling.
version: 1.0.2
homepage: https://github.com/1124863805/http_util_package
repository: https://github.com/1124863805/http_util_package
issue_tracker: https://github.com/1124863805/http_util_package/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  dio: 5.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets needed
